services:
  web:
    build: .
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py init_redis_availability &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - DJANGO_SETTINGS_MODULE=workspace_booking.settings


  redis:
    image: redis:7
    ports:
      - "6379:6379"

  cronjob:
    build:
      context: .
      dockerfile: cron/Dockerfile

  redis-cron:
    build:
      context: .
      dockerfile: cron/Dockerfile
    volumes:
      - .:/code
    depends_on:
      - web
      - redis